slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom          
    map_frame: robot_1/map             
    base_frame: base_link      
    scan_topic: scan           
    mode: "mapping"
    
